export const QUADTREE_CAPACITY = 4;
export const SPACE_VIEW_MAX_WIDTH = 1048576;
export const SPACE_VIEW_MAX_HEIGHT = 1048576;
export const MAXIMUM_N_OBJECTS = 1000;
export const SEARCH_RANGE_FACTOR = 1;