export { Space } from "./src/Space.mjs"
export { Time } from "./src/Time.mjs"
export { V2 } from "./src/math/Vector2.mjs"
export { Object } from "./src/objects/Object.mjs"
export { Properties } from "./src/objects/Properties.mjs"
export { Circle } from "./src/objects/shapes/Circle.mjs"
// export { Rectangle } from "./src/objects/shapes/Rectangle.mjs"
export { Triangle } from "./src/objects/shapes/Triangle.mjs"