export { Space } from "./src/Space.mjs"
export { Time } from "./src/Time.mjs"
export { V2 } from "./src/math/Vector2.mjs"
export { Object } from "./src/objects/Object.mjs"
export { Properties } from "./src/objects/Properties.mjs"
export { Circle } from "./src/objects/shapes/Circle.mjs"
// export { Rectangle } from "./src/objects/shapes/Rectangle.mjs"
export { Triangle } from "./src/objects/shapes/Triangle.mjs"
export { toRadians, toDegrees } from "./src/math/Convert.mjs"
export * from "./ultis/Ultis.module.js"
export * from "./src/Constants.mjs"

// export { toDegrees, toRadians } from "./src/math/Convert.mjs"
// export { timeStart, timeEslapsed, displayTimeEslapsed, funcExeTime } from "./ultis/Debug.mjs"
// export { formatCoord3DPs, formatDPs } from "./ultis/Format.mjs"
// export { curryFunction, groupCurriedFunctions } from "./ultis/Functions.mjs"
// export { strictlyNumber, looselyNumber, looselyV2 } from "./ultis/TypeChecks.mjs"